version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: school-postgres
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - school-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: school-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - school-net

  backend:
    build:
      context: ./school-registry-backend
      dockerfile: Dockerfile
    container_name: school-backend
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - school-net

  frontend:
   build:
    context: ./school-registry-frontend
    dockerfile: Dockerfile
   container_name: school-frontend
   ports:
    - "3000:80"
   depends_on:
    - backend
   networks:
    - school-net

volumes:
  postgres-data:

networks:
  school-net: